#!/bin/bash
./bro -m consumer &
python -m SimpleHTTPServer&
midori http://127.0.0.1:8000 &
sleep 10
sudo mplayer -ao alsa:device=hw -af equalizer=0:0:0:0:0:0:0:0:0:0 -volume 50 http://imagine.1stepstream.com:8000/aac| grep -Po "KVolume.*?%|Title.*?|Album.*?|Year.*?|Track.*?|Name.*?|Website.*?|Genre.*?" | while IFS= read -r line; do echo $line |./bro -m publisher -e default ; done
